<?php

/**
 * @file
 * Contains drup_settings.module.
 */


/**
 * Implements hook_token_info().
 */
function drup_settings_token_info() {
    $tokenType = 'drup_settings';

    $types = [
        $tokenType => [
            'name' => t('DrupSettings Variables'),
            'description' => t('Get custom values from DrupSettings module')
        ]
    ];

    $output = [
        'types' => $types,
        'tokens' => []
    ];

    // @todo config dans DrupSite ?
    $settings = [
        'site_emails_from' => 'Site Emails From',
        'contact_infos_email' => 'Site Email Contact'
    ];

    foreach ($types as $key => $type) {
        $output['tokens'][$key] = [];

        foreach ($settings as $id => $label) {
            $output['tokens'][$key][$id] = [
                'name' => $label . ' (' . $type['name'] . ')',
                'description' => ''
            ];
        }
    }

    return $output;
}

/**
 * Implements hook_tokens().
 *
 * @param $type
 * @param $tokens
 * @param array $data
 * @param array $options
 * @param \Drupal\Core\Render\BubbleableMetadata $bubbleable_metadata
 *
 * @return array
 */
function drup_settings_tokens($type, $tokens, array $data, array $options, \Drupal\Core\Render\BubbleableMetadata $bubbleable_metadata) {
    $tokenType = 'drup_settings';
    $replacements = [];

    if (strpos($type, $tokenType) === 0) {
        /** @var \Drupal\drup_settings\DrupSettings $drupSettings */
        $drupSettings = \Drupal::service('drup_settings');

        foreach ($tokens as $name => $original) {
            $replacements[$original] = $drupSettings->getValue($name);
        }
    }

    return $replacements;
}
